global class LeadCreationAction {
    @InvocableVariable
    global ID objectId;
    
    @InvocableVariable
    global String templateId; 
    
    @InvocableVariable
    global boolean fromLead; 
    
    @InvocableVariable
    global Decimal noOfExpirationdays; 
    
    @InvocableVariable
    global String eventId; 
    
    @InvocableVariable
    global String ownerId; 
    
    @InvocableVariable
    global String eventRelatedToId; 
    
    @InvocableVariable
    global Datetime eventEndDate; 
  }